name: "CI"

on:
  push:
    branches: ["feat/pipelines"]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
  
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1

    - name: Install dependencies
      working-directory: ./backend
      run: |
        docker-compose up -d --build
        docker-compose exec app composer install

    - name: Run PHPStan
      working-directory: ./backend
      run: |
        docker-compose exec app php vendor/bin/phpstan analyse -c phpstan.neon -l 7 src

      