name: "CI"

on:
  push:
    branches: ["feat/pipelines"]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - uses: thenabeel/action-phpcs@v8
        with:
          files: "**.php"
          phpcs_path: php phpcs.phar
          standard: phpcs.xml
  
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - name: Verify backend folder exists
        run: |
          ls backend

    # runs-on: ubuntu-latest
    # steps:
    #   - name: Checkout code
    #     uses: actions/checkout@v2

    #   - name: Install dependencies
    #     run: |
    #       cd backend
    #       composer install

    #   - name: Run PHPStan
    #     run: |
    #       cd backend
    #       ./vendor/bin/phpstan analyse -c phpstan.neon src

    #   - name: Check for errors
    #     run: |
    #       if [ "$(cd backend && ./vendor/bin/phpstan analyse -c phpstan.neon src --error-format=table | grep -c error)" -eq 0 ]; then
    #         echo "No errors detected."
    #       else
    #         echo "Errors detected."
    #         exit 1
    #       fi
